### ISSUE TITLE
Error MissingPackageName: Invalid or missing package.json file at ''. If not using a package.json, pass in a packageName.

### ISSUE THREAD

**Issue by ilanbalink** [jayree/sfdx-plugin-manifest#357]
Hi,

Receiving the following erorr When executing generate:
MissingPackageName: Invalid or missing package.json file at ''. If not using a package.json, pass in a packageName.

Executed Command:
sfdx jayree:manifest:generate -u org-alias

**Comment by jayree** [comment]
@ilanbalink could you please try the latest release v2.3.9 and check if you still see this issue?
